//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 12:45:52 PM IST 
//


package com.student;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.student package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.student
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StudentRegistartionRq }
     * 
     */
    public StudentRegistartionRq createStudentRegistartionRq() {
        return new StudentRegistartionRq();
    }

    /**
     * Create an instance of {@link StudentRegistartionRq.Students }
     * 
     */
    public StudentRegistartionRq.Students createStudentRegistartionRqStudents() {
        return new StudentRegistartionRq.Students();
    }

    /**
     * Create an instance of {@link StudentRegistartionRq.Students.Student }
     * 
     */
    public StudentRegistartionRq.Students.Student createStudentRegistartionRqStudentsStudent() {
        return new StudentRegistartionRq.Students.Student();
    }

    /**
     * Create an instance of {@link StudentRegistartionRs }
     * 
     */
    public StudentRegistartionRs createStudentRegistartionRs() {
        return new StudentRegistartionRs();
    }

    /**
     * Create an instance of {@link StudentRegistartionRq.Students.Student.Address }
     * 
     */
    public StudentRegistartionRq.Students.Student.Address createStudentRegistartionRqStudentsStudentAddress() {
        return new StudentRegistartionRq.Students.Student.Address();
    }

}
